import { WorkOrder, Equipment, Part, KPI, EquipmentStats, EquipmentWorkHistory } from '@/types';

// Nigerian Airport IATA codes for SAHCO operations
export const NIGERIAN_AIRPORTS = [
  { code: 'LOS', name: 'Lagos - Murtala Muhammed Int\'l' },
  { code: 'ABV', name: 'Abuja - Nnamdi Azikiwe Int\'l' },
  { code: 'PHC', name: 'Port Harcourt Int\'l' },
  { code: 'KAN', name: 'Kano - Mallam Aminu Kano Int\'l' },
  { code: 'ENU', name: 'Enugu - Akanu Ibiam Int\'l' },
];

// Expanded work orders with realistic SAHCO data
export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-2025-00145',
    equipmentId: 'EQ-GPU-001',
    equipmentName: 'Ground Power Unit GPU-LOS-01',
    site: 'LOS',
    area: 'Ramp Operations',
    type: 'corrective',
    priority: 'critical',
    title: 'GPU voltage fluctuation - immediate repair needed',
    description: 'Voltage output unstable, ranging from 110V to 130V. Aircraft rejected connection.',
    requester: 'Ramp Supervisor',
    requesterId: 'user-003',
    assignedBy: 'Engr. Adewale Okonkwo',
    assignees: ['Tech. Ibrahim Musa', 'Tech. Chidi Okafor'],
    status: 'verified',
    reportedAt: '2025-01-08T06:30:00Z',
    startedAt: '2025-01-08T07:15:00Z',
    completedAt: '2025-01-08T11:45:00Z',
    verifiedAt: '2025-01-08T14:20:00Z',
    failureCode: 'F-GPU-001',
    causeCode: 'C-ELEC-012',
    remedyCode: 'R-REPL-004',
    safetyTags: ['LOTO Required', 'Electrical Work'],
    attachments: [],
    photos: ['gpu-voltage-meter.jpg'],
    notes: ['Replaced voltage regulator', 'System tested successfully'],
    evidenceMinMet: true,
    stateEnteredAt: '2025-01-08T14:20:00Z',
    laborHours: 4.5,
    partsCost: 187000,
    totalCost: 187000,
    verificationStatus: 'serviceable',
    partsUsed: [
      { partId: 'PT-001', partName: 'Voltage Regulator - 400Hz', quantity: 1, unitCost: 175000 },
      { partId: 'PT-002', partName: 'Electrical Wire Kit', quantity: 1, unitCost: 12000 }
    ],
  },
  {
    id: 'WO-2025-00144',
    equipmentId: 'EQ-BL-002',
    equipmentName: 'Belt Loader BL-LOS-93/2',
    site: 'LOS',
    area: 'Cargo Terminal',
    type: 'corrective',
    priority: 'high',
    title: 'Hydraulic system leak on belt loader',
    description: 'Hydraulic fluid leaking from cylinder seal. Equipment grounded.',
    requester: 'Cargo Operations',
    requesterId: 'user-005',
    assignedBy: 'Engr. Adewale Okonkwo',
    assignees: ['Tech. Ibrahim Musa'],
    status: 'verified',
    reportedAt: '2025-01-07T14:20:00Z',
    startedAt: '2025-01-07T15:00:00Z',
    completedAt: '2025-01-07T18:30:00Z',
    verifiedAt: '2025-01-08T08:15:00Z',
    failureCode: 'F-HYD-003',
    causeCode: 'C-SEAL-001',
    remedyCode: 'R-SEAL-REPL',
    safetyTags: ['LOTO Required', 'Hydraulic Fluid'],
    attachments: [],
    photos: [],
    notes: ['Seal replaced', 'Fluid topped up'],
    evidenceMinMet: true,
    stateEnteredAt: '2025-01-08T08:15:00Z',
    laborHours: 3.5,
    partsCost: 45000,
    totalCost: 45000,
    verificationStatus: 'serviceable',
    partsUsed: [
      { partId: 'PT-003', partName: 'Hydraulic Cylinder Seal Kit', quantity: 1, unitCost: 35000 },
      { partId: 'PT-004', partName: 'Hydraulic Fluid - 5L', quantity: 2, unitCost: 5000 }
    ],
  },
  {
    id: 'WO-2025-00143',
    equipmentId: 'EQ-TUG-003',
    equipmentName: 'Pushback Tug TUG-ABV-104/5',
    site: 'ABV',
    area: 'Ramp Operations',
    type: 'preventive',
    priority: 'medium',
    title: 'Monthly PM - Tug 104/5',
    description: 'Scheduled monthly preventive maintenance including oil change and brake inspection',
    requester: 'System Generated',
    requesterId: 'system',
    assignedBy: 'Planner - Abuja Base',
    assignees: ['Tech. Emeka Nwankwo'],
    status: 'completed',
    reportedAt: '2025-01-05T08:00:00Z',
    startedAt: '2025-01-06T09:00:00Z',
    completedAt: '2025-01-06T11:30:00Z',
    attachments: [],
    photos: [],
    notes: ['Oil changed', 'Brakes inspected - good condition'],
    evidenceMinMet: true,
    stateEnteredAt: '2025-01-06T11:30:00Z',
    laborHours: 2.5,
    partsCost: 28000,
    totalCost: 28000,
    partsUsed: [
      { partId: 'PT-005', partName: 'Engine Oil 15W-40 - 20L', quantity: 1, unitCost: 18000 },
      { partId: 'PT-010', partName: 'Oil Filter', quantity: 2, unitCost: 5000 }
    ],
  },
  {
    id: 'WO-2025-00142',
    equipmentId: 'EQ-PBB-004',
    equipmentName: 'Passenger Boarding Stairs PBB-PHC-22/1',
    site: 'PHC',
    area: 'Ramp Operations',
    type: 'corrective',
    priority: 'high',
    title: 'Stair lift mechanism jammed',
    description: 'Hydraulic lift not responding, stairs stuck in lowered position',
    requester: 'Ground Services PHC',
    requesterId: 'user-008',
    assignedBy: 'Engr. Chioma Eze',
    assignees: ['Tech. Samuel Obi'],
    status: 'verified',
    reportedAt: '2024-12-28T11:15:00Z',
    startedAt: '2024-12-28T12:00:00Z',
    completedAt: '2024-12-28T16:30:00Z',
    verifiedAt: '2024-12-29T09:45:00Z',
    failureCode: 'F-HYD-005',
    causeCode: 'C-PUMP-002',
    remedyCode: 'R-PUMP-REPL',
    safetyTags: ['LOTO Required'],
    attachments: [],
    photos: ['pbb-pump.jpg'],
    notes: ['Replaced hydraulic pump', 'System tested - operational'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-12-29T09:45:00Z',
    laborHours: 4.5,
    partsCost: 320000,
    totalCost: 320000,
    verificationStatus: 'serviceable',
    partsUsed: [
      { partId: 'PT-011', partName: 'Hydraulic Pump Assembly', quantity: 1, unitCost: 320000 }
    ],
  },
  {
    id: 'WO-2025-00141',
    equipmentId: 'EQ-GPU-001',
    equipmentName: 'Ground Power Unit GPU-LOS-01',
    site: 'LOS',
    area: 'Ramp Operations',
    type: 'preventive',
    priority: 'medium',
    title: 'Quarterly PM - GPU-LOS-01',
    description: 'Scheduled quarterly preventive maintenance',
    requester: 'System Generated',
    requesterId: 'system',
    assignedBy: 'Engr. Adewale Okonkwo',
    assignees: ['Tech. Ibrahim Musa'],
    status: 'completed',
    reportedAt: '2024-12-20T08:00:00Z',
    startedAt: '2024-12-21T09:00:00Z',
    completedAt: '2024-12-21T12:00:00Z',
    attachments: [],
    photos: [],
    notes: ['Oil changed', 'Filters replaced', 'All systems checked'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-12-21T12:00:00Z',
    laborHours: 3.0,
    partsCost: 42000,
    totalCost: 42000,
    partsUsed: [
      { partId: 'PT-005', partName: 'Engine Oil 15W-40 - 20L', quantity: 1, unitCost: 18000 },
      { partId: 'PT-010', partName: 'Oil Filter', quantity: 2, unitCost: 5000 },
      { partId: 'PT-012', partName: 'Air Filter', quantity: 2, unitCost: 7000 }
    ],
  },
  {
    id: 'WO-2025-00140',
    equipmentId: 'EQ-BL-002',
    equipmentName: 'Belt Loader BL-LOS-93/2',
    site: 'LOS',
    area: 'Cargo Terminal',
    type: 'preventive',
    priority: 'low',
    title: 'Monthly inspection - Belt Loader 93/2',
    description: 'Routine monthly inspection and lubrication',
    requester: 'System Generated',
    requesterId: 'system',
    assignedBy: 'Engr. Adewale Okonkwo',
    assignees: ['Tech. Chidi Okafor'],
    status: 'completed',
    reportedAt: '2024-12-15T08:00:00Z',
    startedAt: '2024-12-16T10:00:00Z',
    completedAt: '2024-12-16T11:30:00Z',
    attachments: [],
    photos: [],
    notes: ['Lubrication completed', 'No issues found'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-12-16T11:30:00Z',
    laborHours: 1.5,
    partsCost: 5000,
    totalCost: 5000,
    partsUsed: [
      { partId: 'PT-013', partName: 'Multi-Purpose Grease - 1kg', quantity: 5, unitCost: 1000 }
    ],
  },
  {
    id: 'WO-2025-00139',
    equipmentId: 'EQ-FORK-005',
    equipmentName: 'Forklift FORK-LOS-44/8',
    site: 'LOS',
    area: 'Cargo Warehouse',
    type: 'corrective',
    priority: 'medium',
    title: 'Forklift battery not charging',
    description: 'Forklift battery not holding charge, operational time reduced to 2 hours',
    requester: 'Warehouse Supervisor',
    requesterId: 'user-006',
    assignedBy: 'Engr. Adewale Okonkwo',
    assignees: ['Tech. Bola Adeyemi'],
    status: 'completed',
    reportedAt: '2024-12-10T07:30:00Z',
    startedAt: '2024-12-10T09:00:00Z',
    completedAt: '2024-12-10T14:30:00Z',
    failureCode: 'F-ELEC-008',
    causeCode: 'C-BATT-003',
    remedyCode: 'R-BATT-REPL',
    attachments: [],
    photos: [],
    notes: ['Battery replaced', 'Charging system tested - OK'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-12-10T14:30:00Z',
    laborHours: 5.5,
    partsCost: 450000,
    totalCost: 450000,
    partsUsed: [
      { partId: 'PT-006', partName: 'Lead-Acid Battery 48V 400Ah', quantity: 1, unitCost: 450000 }
    ],
  },
  {
    id: 'WO-2025-00138',
    equipmentId: 'EQ-TUG-003',
    equipmentName: 'Pushback Tug TUG-ABV-104/5',
    site: 'ABV',
    area: 'Ramp Operations',
    type: 'corrective',
    priority: 'critical',
    title: 'Tug engine overheating',
    description: 'Engine temperature exceeding normal range, white smoke from exhaust',
    requester: 'Ramp Operations ABV',
    requesterId: 'user-009',
    assignedBy: 'Planner - Abuja Base',
    assignees: ['Tech. Emeka Nwankwo', 'Tech. Fatima Usman'],
    status: 'completed',
    reportedAt: '2024-11-28T13:45:00Z',
    startedAt: '2024-11-28T14:30:00Z',
    completedAt: '2024-11-29T10:15:00Z',
    failureCode: 'F-ENG-004',
    causeCode: 'C-COOL-001',
    remedyCode: 'R-RADI-REPL',
    safetyTags: ['Hot Work'],
    attachments: [],
    photos: ['tug-radiator.jpg'],
    notes: ['Radiator replaced', 'Coolant system flushed', 'Engine tested - normal temp'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-11-29T10:15:00Z',
    laborHours: 8.0,
    partsCost: 285000,
    totalCost: 285000,
    partsUsed: [
      { partId: 'PT-007', partName: 'Radiator Assembly - Heavy Duty', quantity: 1, unitCost: 250000 },
      { partId: 'PT-008', partName: 'Engine Coolant - 20L', quantity: 2, unitCost: 17500 }
    ],
  },
  {
    id: 'WO-2025-00137',
    equipmentId: 'EQ-CAT-006',
    equipmentName: 'Catering Truck CAT-KAN-15/3',
    site: 'KAN',
    area: 'Catering Services',
    type: 'inspection',
    priority: 'low',
    title: 'Annual safety inspection - Catering truck',
    description: 'Required annual safety inspection for catering vehicle',
    requester: 'Safety Officer',
    requesterId: 'user-010',
    assignedBy: 'Engr. Aliyu Hassan',
    assignees: ['Tech. Aisha Mohammed'],
    status: 'completed',
    reportedAt: '2024-11-20T08:00:00Z',
    startedAt: '2024-11-21T09:00:00Z',
    completedAt: '2024-11-21T11:00:00Z',
    attachments: ['safety-cert-2024.pdf'],
    photos: [],
    notes: ['All safety systems operational', 'Certificate issued'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-11-21T11:00:00Z',
    laborHours: 2.0,
    totalCost: 0,
  },
  {
    id: 'WO-2025-00136',
    equipmentId: 'EQ-GPU-007',
    equipmentName: 'Ground Power Unit GPU-PHC-02',
    site: 'PHC',
    area: 'Ramp Operations',
    type: 'corrective',
    priority: 'high',
    title: 'GPU cable reel damaged',
    description: 'Cable reel mechanism broken, cable cannot be retracted properly',
    requester: 'Ramp Supervisor PHC',
    requesterId: 'user-011',
    assignedBy: 'Engr. Chioma Eze',
    assignees: ['Tech. Samuel Obi'],
    status: 'completed',
    reportedAt: '2024-11-15T10:20:00Z',
    startedAt: '2024-11-15T11:00:00Z',
    completedAt: '2024-11-15T15:30:00Z',
    failureCode: 'F-MECH-009',
    causeCode: 'C-WEAR-005',
    remedyCode: 'R-REEL-REPL',
    attachments: [],
    photos: [],
    notes: ['Cable reel replaced', 'Mechanism tested - smooth operation'],
    evidenceMinMet: true,
    stateEnteredAt: '2024-11-15T15:30:00Z',
    laborHours: 4.5,
    partsCost: 125000,
    totalCost: 125000,
    partsUsed: [
      { partId: 'PT-009', partName: 'Cable Reel Assembly', quantity: 1, unitCost: 125000 }
    ],
  },
  // New open work orders
  {
    id: 'WO-2025-00155',
    equipmentId: 'EQ-WATER-008',
    equipmentName: 'Water Service Truck WATER-ENU-08/1',
    site: 'ENU',
    area: 'Ground Services',
    type: 'corrective',
    priority: 'critical',
    title: 'Water pump not functioning',
    description: 'Water pump motor failed, unable to service aircraft',
    requester: 'Ground Services ENU',
    requesterId: 'user-012',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['Electrical Work'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00154',
    equipmentId: 'EQ-CONT-009',
    equipmentName: 'Container Loader CONT-LOS-25/6',
    site: 'LOS',
    area: 'Cargo Terminal',
    type: 'corrective',
    priority: 'high',
    title: 'Loader platform lift mechanism stuck',
    description: 'Platform won\'t raise to full height, limiting container loading capability',
    requester: 'Cargo Operations',
    requesterId: 'user-013',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['LOTO Required', 'Hydraulic System'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00153',
    equipmentId: 'EQ-BAG-010',
    equipmentName: 'Baggage Tractor BAG-ABV-32/4',
    site: 'ABV',
    area: 'Baggage Handling',
    type: 'preventive',
    priority: 'medium',
    title: 'Quarterly PM - Baggage Tractor 32/4',
    description: 'Scheduled quarterly preventive maintenance',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00152',
    equipmentId: 'EQ-LAV-011',
    equipmentName: 'Lavatory Service Truck LAV-PHC-12/9',
    site: 'PHC',
    area: 'Ground Services',
    type: 'corrective',
    priority: 'medium',
    title: 'Vacuum pump losing suction power',
    description: 'Pump suction reduced by approximately 40%, affecting service time',
    requester: 'Ground Services PHC',
    requesterId: 'user-014',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00151',
    equipmentId: 'EQ-PBB-004',
    equipmentName: 'Passenger Boarding Stairs PBB-PHC-22/1',
    site: 'PHC',
    area: 'Ramp Operations',
    type: 'preventive',
    priority: 'low',
    title: 'Monthly inspection - PBB 22/1',
    description: 'Monthly safety and operational inspection',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Comprehensive SAHCO GSE equipment fleet
export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: 'EQ-GPU-001',
    name: 'Ground Power Unit GPU-LOS-01',
    fleetNumber: '78/1',
    equipmentType: 'Ground Power Unit (GPU)',
    site: 'LOS',
    area: 'Ramp Operations',
    asset: 'GPU',
    type: 'Electric GPU',
    manufacturer: 'TLD',
    model: 'GPU-418-CUP',
    serialNumber: 'TLD-2020-GPU-001',
    dateOfPurchase: '2020-03-15',
    purchaseValue: 18500000,
    purchaseCurrency: 'NGN',
    supplier: 'TLD West Africa',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Ground Operations',
    currentCustodian: 'Ramp Team LOS',
    specs: {
      'Output': '115/200V 400Hz',
      'Power': '90 kVA',
      'Frequency': '400 Hz',
      'Cables': '2x 30m'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-12-21',
    nextPM: '2025-03-21',
    totalOperatingHours: 3420,
    mttr: 4.2,
    mttb: 720,
    historyCount: 12,
    totalRepairs: 3,
    totalMaintenanceCost: 271000,
    averageCostPerRepair: 90333,
    totalLaborHours: 10.5,
    createdBy: 'Admin',
    createdDate: '2020-03-15',
  },
  {
    id: 'EQ-BL-002',
    name: 'Belt Loader BL-LOS-93/2',
    fleetNumber: '93/2',
    equipmentType: 'Belt Loader',
    site: 'LOS',
    area: 'Cargo Terminal',
    asset: 'Belt Loader',
    type: 'Conveyor Belt Loader',
    manufacturer: 'Bombelli',
    model: 'BL30E',
    serialNumber: 'BOM-2019-BL-002',
    dateOfPurchase: '2019-08-22',
    purchaseValue: 15500000,
    purchaseCurrency: 'NGN',
    supplier: 'GSE Services Ltd',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Cargo Operations',
    currentCustodian: 'Cargo Team LOS',
    specs: {
      'Belt Width': '600mm',
      'Max Height': '5.5m',
      'Load Capacity': '6000 kg',
      'Speed': 'Variable 0-30m/min'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-16',
    nextPM: '2025-01-16',
    totalOperatingHours: 4890,
    mttr: 2.8,
    mttb: 1440,
    historyCount: 8,
    totalRepairs: 2,
    totalMaintenanceCost: 50000,
    averageCostPerRepair: 25000,
    totalLaborHours: 5.0,
    createdBy: 'Admin',
    createdDate: '2019-08-22',
  },
  {
    id: 'EQ-TUG-003',
    name: 'Pushback Tug TUG-ABV-104/5',
    fleetNumber: '104/5',
    equipmentType: 'Pushback Tug',
    site: 'ABV',
    area: 'Ramp Operations',
    asset: 'Tug',
    type: 'Towbarless Pushback Tug',
    manufacturer: 'Mototok',
    model: 'Spacer 8600',
    serialNumber: 'MOT-2021-TUG-003',
    dateOfPurchase: '2021-05-10',
    purchaseValue: 42000000,
    purchaseCurrency: 'NGN',
    supplier: 'Aviation GSE Nigeria',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Ground Operations',
    currentCustodian: 'Ramp Team ABV',
    specs: {
      'Max Tow': '86 tons',
      'Engine': 'Diesel 180 HP',
      'Max Speed': '35 km/h',
      'Type': 'Towbarless'
    },
    pmCadence: 'Monthly',
    lastPM: '2025-01-06',
    nextPM: '2025-02-06',
    totalOperatingHours: 2150,
    mttr: 5.5,
    mttb: 960,
    historyCount: 6,
    totalRepairs: 2,
    totalMaintenanceCost: 313000,
    averageCostPerRepair: 156500,
    totalLaborHours: 10.5,
    createdBy: 'Admin',
    createdDate: '2021-05-10',
  },
  {
    id: 'EQ-PBB-004',
    name: 'Passenger Boarding Stairs PBB-PHC-22/1',
    fleetNumber: '22/1',
    equipmentType: 'Passenger Boarding Stairs',
    site: 'PHC',
    area: 'Ramp Operations',
    asset: 'Passenger Stairs',
    type: 'Mobile Boarding Stairs',
    manufacturer: 'Guinault',
    model: 'AXO-S250',
    serialNumber: 'GUN-2018-PBB-004',
    dateOfPurchase: '2018-11-05',
    purchaseValue: 12800000,
    purchaseCurrency: 'NGN',
    supplier: 'West Africa Aviation Equipment',
    status: 'serviceable',
    condition: 'Old',
    assignedDepartment: 'Ground Operations',
    currentCustodian: 'Ramp Team PHC',
    specs: {
      'Height Range': '2.5m - 5.5m',
      'Platform Width': '1.2m',
      'Max Load': '8 passengers',
      'Drive': 'Self-propelled'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-05',
    nextPM: '2025-01-05',
    totalOperatingHours: 5680,
    mttr: 4.1,
    mttb: 1200,
    historyCount: 10,
    totalRepairs: 1,
    totalMaintenanceCost: 320000,
    averageCostPerRepair: 320000,
    totalLaborHours: 4.5,
    createdBy: 'Admin',
    createdDate: '2018-11-05',
  },
  {
    id: 'EQ-FORK-005',
    name: 'Forklift FORK-LOS-44/8',
    fleetNumber: '44/8',
    equipmentType: 'Forklift',
    site: 'LOS',
    area: 'Cargo Warehouse',
    asset: 'Forklift',
    type: 'Electric Forklift',
    manufacturer: 'Toyota',
    model: '8FBE20',
    serialNumber: 'TOY-2019-FORK-005',
    dateOfPurchase: '2019-02-20',
    purchaseValue: 8900000,
    purchaseCurrency: 'NGN',
    supplier: 'Toyota Material Handling Nigeria',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Cargo Warehouse',
    currentCustodian: 'Warehouse Team LOS',
    specs: {
      'Capacity': '2000 kg',
      'Lift Height': '4.5m',
      'Battery': '48V 500Ah',
      'Mast': 'Triple Stage'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-11-15',
    nextPM: '2025-01-15',
    totalOperatingHours: 6230,
    mttr: 4.8,
    mttb: 1680,
    historyCount: 5,
    totalRepairs: 1,
    totalMaintenanceCost: 450000,
    averageCostPerRepair: 450000,
    totalLaborHours: 5.5,
    createdBy: 'Admin',
    createdDate: '2019-02-20',
  },
  {
    id: 'EQ-CAT-006',
    name: 'Catering Truck CAT-KAN-15/3',
    fleetNumber: '15/3',
    equipmentType: 'Catering Truck',
    site: 'KAN',
    area: 'Catering Services',
    asset: 'Catering Vehicle',
    type: 'High Lift Catering Truck',
    manufacturer: 'Mallaghan',
    model: 'HLC-5500',
    serialNumber: 'MAL-2020-CAT-006',
    dateOfPurchase: '2020-07-12',
    purchaseValue: 28500000,
    purchaseCurrency: 'NGN',
    supplier: 'Mallaghan Engineering',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Catering Services',
    currentCustodian: 'Catering Team KAN',
    specs: {
      'Max Lift': '5.5m',
      'Platform Size': '3.5m x 2.2m',
      'Load Capacity': '3000 kg',
      'Lift Type': 'Scissor lift'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-10-15',
    nextPM: '2025-01-15',
    totalOperatingHours: 2890,
    mttr: 1.5,
    mttb: 2160,
    historyCount: 3,
    totalRepairs: 1,
    totalMaintenanceCost: 0,
    averageCostPerRepair: 0,
    totalLaborHours: 2.0,
    createdBy: 'Admin',
    createdDate: '2020-07-12',
  },
  {
    id: 'EQ-GPU-007',
    name: 'Ground Power Unit GPU-PHC-02',
    fleetNumber: '78/2',
    equipmentType: 'Ground Power Unit (GPU)',
    site: 'PHC',
    area: 'Ramp Operations',
    asset: 'GPU',
    type: 'Electric GPU',
    manufacturer: 'JBT AeroTech',
    model: 'eGPU 418E',
    serialNumber: 'JBT-2019-GPU-007',
    dateOfPurchase: '2019-09-28',
    purchaseValue: 19200000,
    purchaseCurrency: 'NGN',
    supplier: 'JBT West Africa',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Ground Operations',
    currentCustodian: 'Ramp Team PHC',
    specs: {
      'Output': '115/200V 400Hz',
      'Power': '90 kVA',
      'Frequency': '400 Hz',
      'Cables': '2x 25m'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-11-10',
    nextPM: '2025-02-10',
    totalOperatingHours: 3980,
    mttr: 3.8,
    mttb: 840,
    historyCount: 7,
    totalRepairs: 1,
    totalMaintenanceCost: 125000,
    averageCostPerRepair: 125000,
    totalLaborHours: 4.5,
    createdBy: 'Admin',
    createdDate: '2019-09-28',
  },
  {
    id: 'EQ-WATER-008',
    name: 'Water Service Truck WATER-ENU-08/1',
    fleetNumber: '08/1',
    equipmentType: 'Water Service Truck',
    site: 'ENU',
    area: 'Ground Services',
    asset: 'Water Truck',
    type: 'Potable Water Service',
    manufacturer: 'Vestergaard',
    model: 'V680',
    serialNumber: 'VES-2017-WATER-008',
    dateOfPurchase: '2017-04-18',
    purchaseValue: 16800000,
    purchaseCurrency: 'NGN',
    supplier: 'Vestergaard Nigeria',
    status: 'unserviceable',
    condition: 'Old',
    assignedDepartment: 'Ground Services',
    currentCustodian: 'Ground Services ENU',
    specs: {
      'Tank Capacity': '2500 liters',
      'Pump Flow': '200 L/min',
      'Hose Length': '30m',
      'Filtration': 'Triple stage'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-01',
    nextPM: '2025-01-01',
    totalOperatingHours: 7450,
    mttr: 6.2,
    mttb: 960,
    historyCount: 12,
    totalRepairs: 0,
    totalMaintenanceCost: 0,
    averageCostPerRepair: 0,
    totalLaborHours: 0,
    remarks: 'Currently unserviceable - pump motor failed',
    createdBy: 'Admin',
    createdDate: '2017-04-18',
  },
  {
    id: 'EQ-CONT-009',
    name: 'Container Loader CONT-LOS-25/6',
    fleetNumber: '25/6',
    equipmentType: 'Container/Pallet Loader',
    site: 'LOS',
    area: 'Cargo Terminal',
    asset: 'Container Loader',
    type: 'Main Deck Cargo Loader',
    manufacturer: 'TLD',
    model: 'ALC-16',
    serialNumber: 'TLD-2021-CONT-009',
    dateOfPurchase: '2021-01-25',
    purchaseValue: 38500000,
    purchaseCurrency: 'NGN',
    supplier: 'TLD West Africa',
    status: 'unserviceable',
    condition: 'Fair',
    assignedDepartment: 'Cargo Operations',
    currentCustodian: 'Cargo Team LOS',
    specs: {
      'Max Height': '6m',
      'Platform Size': '5m x 3m',
      'Load Capacity': '16000 kg',
      'Lift Type': 'Hydraulic scissor'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-10-20',
    nextPM: '2025-01-20',
    totalOperatingHours: 1850,
    mttr: 3.5,
    mttb: 1440,
    historyCount: 4,
    totalRepairs: 0,
    totalMaintenanceCost: 0,
    averageCostPerRepair: 0,
    totalLaborHours: 0,
    remarks: 'Platform lift mechanism stuck',
    createdBy: 'Admin',
    createdDate: '2021-01-25',
  },
  {
    id: 'EQ-BAG-010',
    name: 'Baggage Tractor BAG-ABV-32/4',
    fleetNumber: '32/4',
    equipmentType: 'Baggage Tractor',
    site: 'ABV',
    area: 'Baggage Handling',
    asset: 'Tractor',
    type: 'Baggage Towing Tractor',
    manufacturer: 'Charlatte',
    model: 'T135',
    serialNumber: 'CHA-2020-BAG-010',
    dateOfPurchase: '2020-06-14',
    purchaseValue: 7200000,
    purchaseCurrency: 'NGN',
    supplier: 'Charlatte Nigeria',
    status: 'serviceable',
    condition: 'Fair',
    assignedDepartment: 'Baggage Operations',
    currentCustodian: 'Baggage Team ABV',
    specs: {
      'Tow Capacity': '8000 kg',
      'Engine': 'Diesel 35 HP',
      'Max Speed': '25 km/h',
      'Fuel Tank': '40 liters'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-09-12',
    nextPM: '2025-01-12',
    totalOperatingHours: 3150,
    mttr: 2.2,
    mttb: 1920,
    historyCount: 3,
    totalRepairs: 0,
    totalMaintenanceCost: 0,
    averageCostPerRepair: 0,
    totalLaborHours: 0,
    createdBy: 'Admin',
    createdDate: '2020-06-14',
  },
  {
    id: 'EQ-LAV-011',
    name: 'Lavatory Service Truck LAV-PHC-12/9',
    fleetNumber: '12/9',
    equipmentType: 'Lavatory Service Truck',
    site: 'PHC',
    area: 'Ground Services',
    asset: 'Lavatory Truck',
    type: 'Vacuum Waste Service',
    manufacturer: 'Alvest',
    model: 'LST-4000',
    serialNumber: 'ALV-2019-LAV-011',
    dateOfPurchase: '2019-03-08',
    purchaseValue: 14500000,
    purchaseCurrency: 'NGN',
    supplier: 'Alvest Group Nigeria',
    status: 'pending',
    condition: 'Fair',
    assignedDepartment: 'Ground Services',
    currentCustodian: 'Ground Services PHC',
    specs: {
      'Waste Tank': '1000 liters',
      'Fresh Water': '500 liters',
      'Vacuum Pump': '400 m³/h',
      'Hose Length': '25m'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-02',
    nextPM: '2025-01-02',
    totalOperatingHours: 4720,
    mttr: 3.8,
    mttb: 1320,
    historyCount: 7,
    totalRepairs: 0,
    totalMaintenanceCost: 0,
    averageCostPerRepair: 0,
    totalLaborHours: 0,
    remarks: 'Vacuum pump suction reduced - under assessment',
    createdBy: 'Admin',
    createdDate: '2019-03-08',
  },
];

export const MOCK_PARTS: Part[] = [
  {
    id: 'PART-001',
    sku: 'HYD-SEAL-100',
    name: 'Hydraulic Cylinder Seal Kit',
    category: 'Hydraulic Parts',
    uom: 'Kit',
    onHand: 15,
    reserved: 2,
    onOrder: 10,
    min: 8,
    max: 30,
    unitCost: 45000,
    substitutes: ['HYD-SEAL-101'],
  },
  {
    id: 'PART-002',
    sku: 'ELEC-VR-200',
    name: 'Voltage Regulator GPU',
    category: 'Electrical',
    uom: 'EA',
    onHand: 5,
    reserved: 1,
    onOrder: 5,
    min: 3,
    max: 10,
    unitCost: 187000,
  },
  {
    id: 'PART-003',
    sku: 'HYD-PUMP-350',
    name: 'Hydraulic Pump Assembly',
    category: 'Hydraulic Parts',
    uom: 'EA',
    onHand: 3,
    reserved: 0,
    onOrder: 2,
    min: 2,
    max: 8,
    unitCost: 320000,
  },
  {
    id: 'PART-004',
    sku: 'BATT-FORK-48V',
    name: 'Forklift Battery 48V 500Ah',
    category: 'Batteries',
    uom: 'EA',
    onHand: 2,
    reserved: 1,
    onOrder: 3,
    min: 2,
    max: 6,
    unitCost: 450000,
  },
  {
    id: 'PART-005',
    sku: 'ENG-RAD-TUG',
    name: 'Radiator Assembly - Tug',
    category: 'Engine Parts',
    uom: 'EA',
    onHand: 4,
    reserved: 0,
    onOrder: 0,
    min: 2,
    max: 8,
    unitCost: 285000,
  },
  {
    id: 'PART-006',
    sku: 'CABLE-REEL-GPU',
    name: 'GPU Cable Reel Mechanism',
    category: 'Mechanical',
    uom: 'EA',
    onHand: 6,
    reserved: 0,
    onOrder: 0,
    min: 3,
    max: 10,
    unitCost: 125000,
  },
  {
    id: 'PART-007',
    sku: 'OIL-ENG-20W50',
    name: 'Engine Oil 20W-50',
    category: 'Lubricants',
    uom: 'Liter',
    onHand: 200,
    reserved: 20,
    onOrder: 100,
    min: 50,
    max: 300,
    unitCost: 5000,
  },
  {
    id: 'PART-008',
    sku: 'FILT-AIR-UNIV',
    name: 'Air Filter Universal',
    category: 'Filters',
    uom: 'EA',
    onHand: 35,
    reserved: 5,
    onOrder: 20,
    min: 15,
    max: 60,
    unitCost: 12000,
  },
];

export const MANAGER_KPIS: KPI[] = [
  {
    label: 'MTTR (Hours)',
    value: '3.8',
    change: -5,
    trend: 'down',
  },
  {
    label: 'MTTB (Hours)',
    value: '1,245',
    change: 8,
    trend: 'up',
  },
  {
    label: '% Serviceable',
    value: '81.8%',
    change: -3,
    trend: 'down',
  },
  {
    label: 'Open Work Orders',
    value: 5,
    change: -7,
    trend: 'down',
  },
  {
    label: 'Overdue',
    value: 0,
    change: -2,
    trend: 'down',
  },
  {
    label: 'MTD Cost',
    value: '₦1,814,000',
    change: 15,
    trend: 'up',
  },
];

// Helper functions for equipment statistics
export function getEquipmentStats(equipmentId: string): EquipmentStats {
  const workOrders = MOCK_WORK_ORDERS.filter(wo => wo.equipmentId === equipmentId);
  const completedOrders = workOrders.filter(wo => wo.status === 'completed');
  
  const totalCost = completedOrders.reduce((sum, wo) => sum + (wo.totalCost || 0), 0);
  const totalLaborHours = completedOrders.reduce((sum, wo) => sum + (wo.laborHours || 0), 0);
  
  // Find most frequent technician
  const technicianCounts: Record<string, number> = {};
  completedOrders.forEach(wo => {
    wo.assignees.forEach(tech => {
      technicianCounts[tech] = (technicianCounts[tech] || 0) + 1;
    });
  });
  const mostFrequentTechnician = Object.entries(technicianCounts)
    .sort(([, a], [, b]) => b - a)[0]?.[0];

  // Find most frequent assigner
  const assignerCounts: Record<string, number> = {};
  completedOrders.forEach(wo => {
    if (wo.assignedBy) {
      assignerCounts[wo.assignedBy] = (assignerCounts[wo.assignedBy] || 0) + 1;
    }
  });
  const mostFrequentAssigner = Object.entries(assignerCounts)
    .sort(([, a], [, b]) => b - a)[0]?.[0];

  const lastMaintenance = completedOrders.length > 0 
    ? completedOrders.sort((a, b) => 
        new Date(b.completedAt || '').getTime() - new Date(a.completedAt || '').getTime()
      )[0].completedAt 
    : undefined;

  return {
    equipmentId,
    totalWorkOrders: workOrders.length,
    completedWorkOrders: completedOrders.length,
    totalCost,
    averageCostPerRepair: completedOrders.length > 0 ? totalCost / completedOrders.length : 0,
    totalLaborHours,
    averageLaborHoursPerRepair: completedOrders.length > 0 ? totalLaborHours / completedOrders.length : 0,
    mostFrequentTechnician,
    mostFrequentAssigner,
    lastMaintenanceDate: lastMaintenance,
  };
}

export function getEquipmentWorkHistory(equipmentId: string): EquipmentWorkHistory[] {
  const workOrders = MOCK_WORK_ORDERS.filter(wo => wo.equipmentId === equipmentId);
  
  return workOrders.map(wo => ({
    workOrderId: wo.id,
    type: wo.type,
    assignedBy: wo.assignedBy || 'N/A',
    assignedTo: wo.assignees,
    startedAt: wo.startedAt || wo.reportedAt,
    completedAt: wo.completedAt,
    laborHours: wo.laborHours,
    partsCost: wo.partsCost,
    totalCost: wo.totalCost,
    status: wo.status,
  }));
}

export function getEquipmentTechnicians(equipmentId: string): string[] {
  const workOrders = MOCK_WORK_ORDERS.filter(wo => wo.equipmentId === equipmentId);
  const technicians = new Set<string>();
  
  workOrders.forEach(wo => {
    wo.assignees.forEach(tech => technicians.add(tech));
  });
  
  return Array.from(technicians);
}

export function getEquipmentPlanners(equipmentId: string): string[] {
  const workOrders = MOCK_WORK_ORDERS.filter(wo => wo.equipmentId === equipmentId);
  const planners = new Set<string>();
  
  workOrders.forEach(wo => {
    if (wo.assignedBy) planners.add(wo.assignedBy);
  });
  
  return Array.from(planners);
}