import { WorkOrder, Equipment, Part, KPI } from '@/types';

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-2025-00145',
    equipmentId: 'EQ-7821',
    equipmentName: 'Boiler #2 - Main Plant',
    site: 'Site A',
    area: 'Utilities',
    type: 'corrective',
    priority: 'critical',
    title: 'Boiler pressure relief valve malfunction',
    description: 'Safety relief valve not responding correctly during pressure test. Immediate attention required for safety compliance.',
    requester: 'Mike Davis',
    requesterId: 'user-003',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['LOTO Required', 'Confined Space', 'Hot Work'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    laborHours: 0,
    partsCost: 0,
    totalCost: 0,
  },
  {
    id: 'WO-2025-00144',
    equipmentId: 'EQ-5512',
    equipmentName: 'Compressor Station C1',
    site: 'Site A',
    area: 'Production',
    line: 'Line C',
    type: 'corrective',
    priority: 'high',
    title: 'Air compressor overheating during operation',
    description: 'Temperature sensors showing readings 15°C above normal operating range. Oil levels checked - normal.',
    requester: 'Operations Staff',
    requesterId: 'user-005',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['LOTO Required'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00143',
    equipmentId: 'EQ-9234',
    equipmentName: 'Conveyor Belt A5',
    site: 'Site A',
    area: 'Warehouse',
    line: 'Line A',
    type: 'corrective',
    priority: 'medium',
    title: 'Belt tracking off-center causing product spillage',
    description: 'Conveyor belt is running approximately 2 inches off-center on return side. Minor product spillage observed.',
    requester: 'Sarah Johnson',
    requesterId: 'user-002',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 40 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00142',
    equipmentId: 'EQ-3347',
    equipmentName: 'Robotic Welder #4',
    site: 'Site A',
    area: 'Assembly',
    line: 'Line B',
    type: 'corrective',
    priority: 'high',
    title: 'Weld quality inconsistent - program calibration needed',
    description: 'QC inspection failed on last batch. Weld penetration depth varying by more than acceptable tolerance.',
    requester: 'Quality Control',
    requesterId: 'user-008',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['Hot Work', 'PPE Required'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00141',
    equipmentId: 'EQ-6678',
    equipmentName: 'Cooling Tower CT-02',
    site: 'Site A',
    area: 'Utilities',
    type: 'preventive',
    priority: 'medium',
    title: 'Quarterly cooling tower inspection and cleaning',
    description: 'Scheduled quarterly preventive maintenance including water treatment, fill inspection, and fan motor lubrication.',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00140',
    equipmentId: 'EQ-1123',
    equipmentName: 'Forklift #7',
    site: 'Site A',
    area: 'Warehouse',
    type: 'inspection',
    priority: 'low',
    title: 'Monthly forklift safety inspection',
    description: 'Routine safety inspection including brakes, steering, lights, horn, and hydraulic system check.',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 60 * 60 * 60 * 1000).toISOString(),
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00139',
    equipmentId: 'EQ-8845',
    equipmentName: 'Emergency Generator #1',
    site: 'Site A',
    area: 'Utilities',
    type: 'preventive',
    priority: 'high',
    title: 'Generator monthly load test and oil analysis',
    description: 'Monthly load bank test for 1 hour at 75% capacity. Oil sample to be sent to lab for analysis.',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'open',
    reportedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    safetyTags: ['LOTO Required'],
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'WO-2025-00138',
    equipmentId: 'EQ-4492',
    equipmentName: 'Pump #3 - Line A',
    site: 'Site A',
    area: 'Production',
    line: 'Line A',
    type: 'corrective',
    priority: 'high',
    title: 'Pump vibration exceeding normal levels',
    description: 'Operators reported unusual vibration and noise from pump during normal operation. Bearing replacement likely needed.',
    requester: 'Operations Staff',
    requesterId: 'user-005',
    assignees: ['John Smith'],
    status: 'in_progress',
    reportedAt: '2025-01-10T08:30:00Z',
    scheduledAt: '2025-01-10T10:00:00Z',
    startedAt: '2025-01-10T10:15:00Z',
    dueBy: '2025-01-09T16:00:00Z', // Overdue
    failureCode: 'F-004',
    causeCode: 'C-012',
    remedyCode: 'R-004',
    safetyTags: ['LOTO Required', 'Hot Work'],
    attachments: [],
    photos: [],
    notes: ['Bearing replacement likely needed', 'Ordered parts from stores'],
    evidenceMinMet: false,
    stateEnteredAt: '2025-01-10T10:15:00Z',
    laborHours: 2.5,
    partsCost: 245.50,
    totalCost: 245.50,
  },
  {
    id: 'WO-2025-00137',
    equipmentId: 'EQ-2341',
    equipmentName: 'Conveyor Belt C2',
    site: 'Site A',
    area: 'Warehouse',
    line: 'Line C',
    type: 'preventive',
    priority: 'medium',
    title: 'Monthly PM - Conveyor Belt C2',
    description: 'Scheduled preventive maintenance including lubrication and tension check',
    requester: 'System Generated',
    requesterId: 'system',
    assignees: [],
    status: 'assigned',
    reportedAt: '2025-01-09T06:00:00Z',
    scheduledAt: '2025-01-11T09:00:00Z',
    dueBy: '2025-01-11T12:00:00Z',
    attachments: [],
    photos: [],
    notes: [],
    evidenceMinMet: false,
    stateEnteredAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'WO-2025-00136',
    equipmentId: 'EQ-8821',
    equipmentName: 'HVAC Unit - Building 1',
    site: 'Site A',
    area: 'Facilities',
    type: 'corrective',
    priority: 'critical',
    title: 'Complete HVAC failure - no cooling',
    description: 'HVAC unit not responding, building temperature rising rapidly',
    requester: 'Facilities Manager',
    requesterId: 'user-006',
    assignees: ['user-001', 'user-007'],
    status: 'completed',
    reportedAt: '2025-01-09T14:20:00Z',
    scheduledAt: '2025-01-09T14:30:00Z',
    startedAt: '2025-01-09T14:45:00Z',
    completedAt: '2025-01-09T18:30:00Z',
    dueBy: '2025-01-09T20:00:00Z',
    safetyTags: ['Electrical Work'],
    attachments: [],
    photos: ['photo1.jpg', 'photo2.jpg'],
    notes: ['Replaced compressor', 'System tested and operational'],
    evidenceMinMet: true,
    stateEnteredAt: '2025-01-09T18:30:00Z',
    laborHours: 3.75,
    partsCost: 2850.00,
    totalCost: 3225.00,
  },
  {
    id: 'WO-2025-00135',
    equipmentId: 'EQ-1523',
    equipmentName: 'CNC Machine M5',
    site: 'Site A',
    area: 'Machining',
    line: 'Line B',
    type: 'inspection',
    priority: 'low',
    title: 'Annual calibration check',
    description: 'Required annual calibration and accuracy verification',
    requester: 'Quality Control',
    requesterId: 'user-008',
    assignees: ['user-009'],
    status: 'verified',
    reportedAt: '2025-01-08T09:00:00Z',
    scheduledAt: '2025-01-09T08:00:00Z',
    startedAt: '2025-01-09T08:15:00Z',
    completedAt: '2025-01-09T11:00:00Z',
    verifiedAt: '2025-01-09T14:00:00Z',
    dueBy: '2025-01-12T17:00:00Z',
    attachments: ['calibration-cert.pdf'],
    photos: ['cal-photo.jpg'],
    notes: ['All measurements within spec'],
    evidenceMinMet: true,
    stateEnteredAt: '2025-01-09T14:00:00Z',
    verificationStatus: 'serviceable',
    laborHours: 2.75,
    totalCost: 275.00,
  },
];

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: 'EQ-4492',
    name: 'Pump #3 - Line A',
    site: 'Site A',
    area: 'Production',
    line: 'Line A',
    asset: 'Pump',
    type: 'Centrifugal Pump',
    manufacturer: 'FlowTech',
    model: 'CT-5500',
    serialNumber: 'FT-2019-4492',
    status: 'serviceable',
    specs: {
      'Flow Rate': '500 GPM',
      'Head': '150 ft',
      'Motor': '50 HP',
      'Power': '460V 3-Phase'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-15',
    nextPM: '2025-01-15',
    mttr: 3.2,
    mttb: 720,
    historyCount: 24,
  },
  {
    id: 'EQ-2341',
    name: 'Conveyor Belt C2',
    site: 'Site A',
    area: 'Warehouse',
    line: 'Line C',
    asset: 'Conveyor',
    type: 'Belt Conveyor',
    manufacturer: 'ConveyPro',
    model: 'BP-2400',
    serialNumber: 'CP-2020-2341',
    status: 'serviceable',
    specs: {
      'Length': '100 ft',
      'Width': '36 in',
      'Speed': 'Variable 0-300 FPM',
      'Load Capacity': '5000 lbs'
    },
    pmCadence: 'Monthly',
    lastPM: '2024-12-20',
    nextPM: '2025-01-20',
    mttr: 1.5,
    mttb: 1440,
    historyCount: 12,
  },
  {
    id: 'EQ-8821',
    name: 'HVAC Unit - Building 1',
    site: 'Site A',
    area: 'Facilities',
    asset: 'HVAC',
    type: 'Rooftop Unit',
    manufacturer: 'ClimateCorp',
    model: 'RTU-500',
    serialNumber: 'CC-2018-8821',
    status: 'serviceable',
    specs: {
      'Capacity': '50 Tons',
      'Refrigerant': 'R-410A',
      'Power': '208V 3-Phase',
      'Coverage': '25,000 sq ft'
    },
    pmCadence: 'Quarterly',
    lastPM: '2024-10-15',
    nextPM: '2025-01-15',
    mttr: 4.5,
    mttb: 2160,
    historyCount: 8,
  },
];

export const MOCK_PARTS: Part[] = [
  {
    id: 'PART-001',
    sku: 'BRG-6205',
    name: 'Ball Bearing 6205',
    category: 'Bearings',
    uom: 'EA',
    onHand: 24,
    reserved: 2,
    onOrder: 0,
    min: 10,
    max: 50,
    unitCost: 15.50,
    substitutes: ['BRG-6205-2RS'],
  },
  {
    id: 'PART-002',
    sku: 'SEAL-V100',
    name: 'Mechanical Seal V100',
    category: 'Seals',
    uom: 'EA',
    onHand: 8,
    reserved: 1,
    onOrder: 10,
    min: 5,
    max: 20,
    unitCost: 125.00,
  },
  {
    id: 'PART-003',
    sku: 'BELT-A42',
    name: 'V-Belt A42',
    category: 'Power Transmission',
    uom: 'EA',
    onHand: 12,
    reserved: 0,
    onOrder: 0,
    min: 8,
    max: 30,
    unitCost: 22.75,
    substitutes: ['BELT-A43'],
  },
];

export const MANAGER_KPIS: KPI[] = [
  {
    label: 'MTTR (Hours)',
    value: '3.2',
    change: -8,
    trend: 'down',
  },
  {
    label: 'MTTB (Hours)',
    value: '856',
    change: 12,
    trend: 'up',
  },
  {
    label: '% Serviceable',
    value: '94.2%',
    change: 2,
    trend: 'up',
  },
  {
    label: 'Open Work Orders',
    value: 47,
    change: -5,
    trend: 'down',
  },
  {
    label: 'Overdue',
    value: 3,
    change: -2,
    trend: 'down',
  },
  {
    label: 'MTD Cost',
    value: '$42,350',
    change: 5,
    trend: 'up',
  },
];
